name: vgrowz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  mqtt_client: ^9.8.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/icon_aplikasi.png
    - assets/images/logo_vgrowz.png
    - assets/images/logo_vgrowz_putih.png
    - assets/images/logo_p2mw.png
